name: Split

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  split-provider:
    name: ${{ matrix.provider.folder }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        provider:
          - { folder: be-bpost  , repository: jbelien/geocoder-php-bpost-provider  , branch: "3.x" }
          - { folder: be-geopunt, repository: jbelien/geocoder-php-geopunt-provider, branch: "2.x" }
          - { folder: be-spw    , repository: jbelien/geocoder-php-spw-provider    , branch: "3.x" }
          - { folder: be-urbis  , repository: jbelien/geocoder-php-urbis-provider  , branch: "2.x" }
          - { folder: fr-addok  , repository: jbelien/geocoder-php-addok-provider  , branch: "2.x" }
    steps:
      - name: Install Git Filter Repo
        shell: bash
        run: |
          wget -P /usr/local/bin https://raw.githubusercontent.com/newren/git-filter-repo/main/git-filter-repo
          chmod +x /usr/local/bin/git-filter-repo
      - uses: actions/checkout@v7
        with:
          token: ${{ secrets.GEOCODER_SPLIT_PAT }}
          fetch-depth: 0
      - name: Detect changes
        uses: dorny/paths-filter@v4
        id: changes
        with:
          list-files: shell
          filters: |
            directory:
              - "${{ matrix.provider.folder }}/**"
      - name: Filter Repo
        if: steps.changes.outputs.directory == 'true'
        shell: bash
        run: |
          git filter-repo --debug --force --subdirectory-filter "${{ matrix.provider.folder }}/"
      - name: Push to separate repository
        if: steps.changes.outputs.directory == 'true'
        shell: bash
        run: |
          git remote add provider "https://x-access-token:${{ secrets.GEOCODER_SPLIT_PAT }}@github.com/${{ matrix.provider.repository }}.git"
          git ls-remote provider
          git push --force --set-upstream provider "HEAD:${{ matrix.provider.branch }}"
